name: CI

on:
  push:


jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      ts: ${{ steps.changes.outputs.ts }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=ts::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .ts$ | xargs)"
  
  make_check:
    runs-on: ubuntu-latest
    needs: changedfiles
    steps:
      - name: get env
        run: env  
    
      - name: Get changed files
       
    # only run there are changed files
       # if: ${{needs.changedfiles.outputs.ts}}
        
      - name: echo changed files
        run: echo ${{needs.changedfiles.outputs.ts}}    
      - name: Send mail      
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
   
    # Required mail server address if not connection_url:
           server_address: smtp.gmail.com
           server_port: 465
    # Optional whether this connection use TLS (default is true if server_port is 465)
           secure: true
    # Optional (recommended): mail server username:
           username:  ${{ secrets.MAIL_USERNAME}} 
 
    # Optional (recommended) mail server password:
           password: ${{secrets.MAIL_PASSWORD}}
         
           
    # Required mail subject:
           subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}    # Required recipients' addresses:
           to: bhavani@hpe.com
    # Required sender full name (address can be skipped):
           from: chapel-lang github actions 
    # Optional plain body:
   
           body: |
              
               ${{ github.job }} job in worflow
              
              # Optional HTML body read from file:
           html_body: |
              <!DOCTYPE html>
              <html>
              <body>
              <h1>${{ github.job }} job in worflow </h1>
              <p>   
              ${{ github.job }} job in worflow <br>
              branch ${{github.ref}} <br>
              commit id : ${{ github.event.head_commit.id }} <br>
              commit message: ${{ github.event.head_commit.message }}  <br>
              sha: ${{ github.head_ref }}.${{ github.sha }}<br>
              files changed: ${{changedfiles.outputs.ts}}
              ${{ github.event.workflow }} of ${{ github.repository }} 
              has ${{ job.status }}   <br>
              </p>
              </body>
              </html>
    # Optional carbon copy recipients:
    #cc: kyloren@example.com,leia@example.com
    # Optional blind carbon copy recipients:
    #bcc: r2d2@example.com,hansolo@example.com
    # Optional recipient of the email response:
    #reply_to: luke@example.com
    # Optional Message ID this message is replying to:
    #in_reply_to: <random-luke@example.com>
    # Optional unsigned/invalid certificates allowance:
    #       ignore_cert: true
    # Optional converting Markdown to HTML (set content_type to text/html too):
           convert_markdown: true
    # Optional attachments:
           attachments: attachments.zip,git.diff,./dist/static/*.js
    # Optional priority: 'high', 'normal' (default) or 'low'
           priority: low
