name: CI

on:
  push:

# NOTE: each job has to specify the container section in its entirety, which is
# certainly repetetive, but the `defaults` section can't be applied and the `env`
# context isn't available in the `jobs` section
#   [1] https://docs.github.com/en/actions/learn-github-actions/contexts#about-contexts
#   [2] https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs
# And other yml features like anchors and merge aren't supported
#   [3] https://github.com/actions/starter-workflows/issues/162

jobs:
  make_check:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
    # Specify connection via URL (replaces server_address, server_port, secure,
    # username and password)
    #
    # Format:
    #
    #  * smtp://user:password@server:port
    #  * smtp+starttls://user:password@server:port
    #       connection_url: ${{secrets.MAIL_CONNECTION}}
    # Required mail server address if not connection_url:
           server_address: smtp.gmail.com
    # Server port, default 25:
           server_port: 465
    # Optional whether this connection use TLS (default is true if server_port is 465)
           secure: true
    # Optional (recommended): mail server username:
           username: ${{secrets.USERNAME}}
           #username: chapelhpc@gmail.com
    # Optional (recommended) mail server password:
           password: ${{secrets.PASSWORD}}
           # password: dandfgyudekkjbhi    
           
    # Required mail subject:
           subject: Chapel
    # Required recipients' addresses:
           to: bhavani@hpe.com
    # Required sender full name (address can be skipped):
           from: chapelhpc@gmail.com
    # Optional plain body:
           body: ${{matrix.body}}
    #  body: Build job of ${{github.repository}} completed successfully!
    # Optional HTML body read from file:
    #       html_body: file://README.html
    # Optional carbon copy recipients:
    #cc: kyloren@example.com,leia@example.com
    # Optional blind carbon copy recipients:
    #bcc: r2d2@example.com,hansolo@example.com
    # Optional recipient of the email response:
    #reply_to: luke@example.com
    # Optional Message ID this message is replying to:
    #in_reply_to: <random-luke@example.com>
    # Optional unsigned/invalid certificates allowance:
    #       ignore_cert: true
    # Optional converting Markdown to HTML (set content_type to text/html too):
    #       convert_markdown: true
    # Optional attachments:
    #       attachments: attachments.zip,git.diff,./dist/static/*.js
    # Optional priority: 'high', 'normal' (default) or 'low'
    #       priority: low
