name: CI

on:
  push:


jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      ts: ${{ steps.changes.outputs.ts }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
         fetch-depth: 0

      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=ts::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .ts$ | xargs)"
  
  send_email:
    runs-on: ubuntu-latest
    needs: changedfiles
    steps:
      - name: get env
        run: env       
      - name: get git events
        run:  cat "$GITHUB_EVENT_PATH"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"  
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v32

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done    
          
      - name: Send mail      
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
   
    # Required mail server address if not connection_url:
           server_address: smtp.gmail.com
           server_port: 465
    # Optional whether this connection use TLS (default is true if server_port is 465)
           secure: true
    # Optional (recommended): mail server username:
           username:  ${{ secrets.MAIL_USERNAME}} 
 
    # Optional (recommended) mail server password:
           password: ${{secrets.MAIL_PASSWORD}}
         
           
    # Required mail subject:
           subject: Chapel Merge ${{ github.event.head_commit.message }}  
           # Required recipients' addresses:
           to: bhavani@hpe.com
    # Required sender full name (address can be skipped):
           from: chapel-lang github actions 
    # Optional plain body:
   
           body: |
              
               ${{ github.job }} job in worflow
              
              # Optional HTML body read from file:
           html_body: |
              <!DOCTYPE html>
              <html>
              <body>
              <h1>${{ github.event.head_commit.author.name}} </h1>
              <p>   
              <br>
              Branch ${{github.ref}} <br>
              Author: ${{ github.event.head_commit.author.name}} <br>
              Revision: ${{github.event.repository.id}}  <br>
              Commit id : ${{ github.event.head_commit.id }} <br>
              Commit message: ${{ github.event.head_commit.message }}  <br>
              Sha: ${{ github.head_ref }}.${{ github.sha }}<br>
              Link: ${{github.event.head_commit.url}} <br> 
              Log Message: ${{github.event.commits.message}} <br>
              Modified Files: ${{github.event.repository.compare}} <br>
              </p>
              </body>
              </html>
    # Optional carbon copy recipients:
    #cc: kyloren@example.com,leia@example.com
    # Optional blind carbon copy recipients:
    #bcc: r2d2@example.com,hansolo@example.com
    # Optional recipient of the email response:
    #reply_to: luke@example.com
    # Optional Message ID this message is replying to:
    #in_reply_to: <random-luke@example.com>
    # Optional unsigned/invalid certificates allowance:
    #       ignore_cert: true
    # Optional converting Markdown to HTML (set content_type to text/html too):
           convert_markdown: true
    # Optional attachments:
           attachments: attachments.zip,git.diff,./dist/static/*.js
    # Optional priority: 'high', 'normal' (default) or 'low'
           priority: low
