name: CI

on:
  push:


jobs:
  
  
  send_email:
    runs-on: ubuntu-latest
  
    steps:
      - name: get env
        run: env       
      - name: get git events
        run:  cat "$GITHUB_EVENT_PATH"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"  
        
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v32
          
      - name: Send mail      
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
   
    # Required mail server address if not connection_url:
           server_address: smtp.gmail.com
           server_port: 465
    # Optional whether this connection use TLS (default is true if server_port is 465)
           secure: true
    # Optional (recommended): mail server username:
           username:  ${{ secrets.MAIL_USERNAME}} 
 
    # Optional (recommended) mail server password:
           password: ${{secrets.MAIL_PASSWORD}}
         
           
    # Required mail subject:
           subject: Chapel Merge ${{ github.event.head_commit.message }}  
           # Required recipients' addresses:
           to: bhavani@hpe.com
    # Required sender full name (address can be skipped):
           from: chapel-lang 
    # Optional plain body:
   
           body: |
              
               ${{ github.job }} job in worflow
              
              # Optional HTML body read from file:
           html_body: |
              <!DOCTYPE html>
              <html>
              <body>
             
              <p>   
              <br>
              <br>
              <br>
              Branch ${{github.ref}} <br>
              Author: ${{ github.event.head_commit.author.name}} <br>
              Revision: ${{github.event.repository.id}}  <br>
              Commit id : ${{ github.event.head_commit.id }} <br>
              Commit message: ${{ github.event.head_commit.message }}  <br>
              Sha: ${{ github.head_ref }}.${{ github.sha }}<br>
              Link: ${{github.event.head_commit.url}} <br> 
              Log Message: ${{github.event.commit.message}} <br>  
              Compare: ${{github.event.compare}} <br>
              Modified Files: <br>
              ${{steps.changed-files.outputs.all_changed_and_modified_files}} <br>
              ${{steps.changed-files.outputs.deleted_files}} <br>
              </p>
              </body>
              </html>
    # Optional carbon copy recipients:
    #cc: kyloren@example.com,leia@example.com
    # Optional blind carbon copy recipients:
    #bcc: r2d2@example.com,hansolo@example.com
    # Optional recipient of the email response:
    #reply_to: luke@example.com
    # Optional Message ID this message is replying to:
    #in_reply_to: <random-luke@example.com>
    # Optional unsigned/invalid certificates allowance:
    #       ignore_cert: true
    # Optional converting Markdown to HTML (set content_type to text/html too):
           convert_markdown: true
    # Optional attachments:
           attachments: attachments.zip,git.diff,./dist/static/*.js
    # Optional priority: 'high', 'normal' (default) or 'low'
           priority: low
