name: CI

on:
  push:

# NOTE: each job has to specify the container section in its entirety, which is
# certainly repetetive, but the `defaults` section can't be applied and the `env`
# context isn't available in the `jobs` section
#   [1] https://docs.github.com/en/actions/learn-github-actions/contexts#about-contexts
#   [2] https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs
# And other yml features like anchors and merge aren't supported
#   [3] https://github.com/actions/starter-workflows/issues/162

jobs:
  make_check:
    runs-on: ubuntu-latest
    
    steps:
      - name: get env
        run: env    
    
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
   
    # Required mail server address if not connection_url:
           server_address: smtp.gmail.com
           server_port: 465
    # Optional whether this connection use TLS (default is true if server_port is 465)
           secure: true
    # Optional (recommended): mail server username:
           username:  ${{ secrets.MAIL_USERNAME}} 
 
    # Optional (recommended) mail server password:
           password: ${{secrets.MAIL_PASSWORD}}
         
           
    # Required mail subject:
           subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}    # Required recipients' addresses:
           to: bhavani@hpe.com
    # Required sender full name (address can be skipped):
           from: chapel-lang github actions 
    # Optional plain body:
   
           body: |
              
               ${{ github.job }} job in worflow
              
              # Optional HTML body read from file:
           html_body: |
              <!DOCTYPE html>
              <html>
              <body>
              <h1>${{ github.job }} job in worflow </h1>
              <p>   
              ${{ github.job }} job in worflow <br>
              branch ${{GITHUB_REF#refs/heads/}} <br>
              commit id : ${{ github.event.head_commit.id }} <br>
              commit message: ${{ github.event.head_commit.message }}  <br>
              sha: ${{ github.head_ref }}.${{ github.sha }}<br>
              files changed: ${{ github.event.compare_url }} <br>
              ${{ github.event.workflow }} of ${{ github.repository }} 
              has ${{ job.status }}   <br>
              </p>
              </body>
              </html>
    # Optional carbon copy recipients:
    #cc: kyloren@example.com,leia@example.com
    # Optional blind carbon copy recipients:
    #bcc: r2d2@example.com,hansolo@example.com
    # Optional recipient of the email response:
    #reply_to: luke@example.com
    # Optional Message ID this message is replying to:
    #in_reply_to: <random-luke@example.com>
    # Optional unsigned/invalid certificates allowance:
    #       ignore_cert: true
    # Optional converting Markdown to HTML (set content_type to text/html too):
           convert_markdown: true
    # Optional attachments:
           attachments: attachments.zip,git.diff,./dist/static/*.js
    # Optional priority: 'high', 'normal' (default) or 'low'
           priority: low
